# Recurrent Slot Attention Configuration
# TTT3R-inspired update mechanism

num_slots: 8
slot_dim: 128
feature_dim: 384  # From TTT3R backbone

# Slot attention parameters
attention:
  num_iterations: 3
  hidden_dim: 256
  mlp_hidden_dim: 512
  
# Slot initialization
initialization:
  method: "learned"  # or "random"
  share_across_frames: false
  
# TTT3R-inspired update rule
update_rule:
  type: "confidence_weighted"
  learning_rate: 0.1
  confidence_threshold: 0.5
  use_gradient_descent: true
  
# Recurrent state
recurrent:
  enabled: true
  state_type: "slots"  # Previous slots as fast weights
  
# Optional: positional encoding
positional_encoding:
  enabled: true
  type: "learned"
