# Default Training Configuration

# Experiment settings
experiment:
  name: "post3r_default"
  seed: 42
  output_dir: "outputs"
  
# Model components
model:
  backbone: "configs/model/backbone.yaml"
  slot_attention: "configs/model/slot_attention.yaml"
  decoder: "configs/model/decoder.yaml"

# Training settings
training:
  batch_size: 4
  num_workers: 8
  max_epochs: 100
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  
  # Video clip settings
  video:
    sequence_length: 16  # Frames per training clip
    frame_skip: 1
    
# Optimizer
optimizer:
  type: "AdamW"
  lr: 1.0e-4
  weight_decay: 0.01
  betas: [0.9, 0.999]
  
# Learning rate scheduler
scheduler:
  type: "cosine"
  warmup_epochs: 5
  min_lr: 1.0e-6
  
# Loss weights
loss:
  reconstruction_3d: 1.0
  # Optional auxiliary losses can be added here
  
# Logging
logging:
  log_every_n_steps: 100
  save_checkpoint_every_n_epochs: 5
  visualize_every_n_steps: 500
  
# Validation
validation:
  check_val_every_n_epoch: 1
  num_val_batches: 50
  
# Hardware
device: "cuda"
precision: "bf16"  # or "fp32", "fp16"
num_gpus: 1
